config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  devise_for :cashiers
  root 'dashboard#index'
  get 'history' => 'dashboard#transactions'
  # API endpoints
  get 'menu' => 'endpoints#menu'
  get 'orders' => 'endpoints#orders'
  get 'transactions' => 'endpoints#transactions'
  get 'order/:order_id' => 'endpoints#order'
  get 'order/:order_id/items' => 'endpoints#order_items'
  get 'order/:order_id/transactions' => 'endpoints#order_transactions'
  get 'transaction/:transaction_id' => 'endpoints#transaction'
  post 'order/new' => 'endpoints#create_order'
  post 'transaction/new' => 'endpoints#create_transaction'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :order_items
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :transactions
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @order_stats = Order.all
    @orders = Order.paginate(:page => params[:page], :per_page => 10)
    @transactions = Transaction.all
    @topfoods = OrderItem.order("order_id DESC").offset(3).limit(3)
  end

  def transactions
    @orders = Order.paginate(:page => params[:page], :per_page => 10)
  end

end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_order, only: [:order, :order_items, :order_transactions, :create_transaction]
  before_action :set_transaction, only: [:transaction]
  include Response
  include ExceptionHandler


  def menu
    @menu = Menu.all
    json_response(@menu)
  end

  def create_order
    @order = Order.new(order_params)
    @order.save!
    json_response(@order)
  end

  def orders
    @orders = Order.all
    json_response(@orders)
  end

  def order
    json_response(@order)
  end

  def order_items
    @order_items = @order.order_items
    json_response(@order_items)
  end

  def create_transaction
    @transaction = Transaction.create!(transaction_params)
    json_response(@order.transactions.last)
  end

  def order_transactions
    @transactions = @order.transactions
    json_response(@transactions)
  end

  def transactions
    @transactions = Transaction.all
    json_response(@transactions)
  end

  def transaction
    json_response(@transaction)
  end

  private

  def set_order
    @order = Order.find(params[:order_id])
  end

  def set_transaction
    @transaction = Transaction.find(params[:transaction_id])
  end

  def order_params
    params.permit(:table_no)
  end

  def transaction_params
    params.permit(:transaction_amount, :transaction_channel, :order_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/endpoints_helper.rb
module EndpointsHelper
end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col s4">
    <div class="card browns">
      <h4><%= @order_stats.count %> Orders</h4>
      <h5><%= number_to_currency(@order_stats.sum(:order_cost), unit: 'KES ') %></h5>
    </div>
  </div>
  <div class="col s4">
    <div class="card reds">
      <h4><%= @order_stats.where(status: true).count %> Paid Orders</h4>
      <h5><%= number_to_currency(@order_stats.where(status: true).sum(:order_cost), unit: "KES ") %></h5>
    </div>
  </div>
  <div class="col s4">
    <div class="card khakis">
      <h5><%= @transactions.count %> Transactions</h5>
      <h4><%= number_to_currency(@transactions.sum(:transaction_amount), unit: "KES ") %></h4>
    </div>
  </div>
</div>

<!-- Tables -->
  <!-- if account_signed_in? || cashier_signed_in? -->
  <h5>Filter Data</h5>
  <div class="filter-form">
    <form class="" action="index.html" method="post">
      <div class="row">
        <div class="col s5">
          <input type="text" name="" value="start date">
        </div>
        <div class="col s5">
          <input type="text" name="" value="end date">
        </div>
        <div class="col s2">
          <button class="btn white" type="button" name="button">search</button>
        </div>
      </div>

    </form>
  </div>
  <div class="search">
    <div class="row">
      <div class="col 11">
        <input type="text" name="" placeholder="Enter Transaction Ref/ Order Ref or Phone No.">
      </div>
      <div class="col 1">
        <a href="#"><i class="material-icons">search</i></a>
      </div>
    </div>
  </div>
    <h1>Orders</h1>
    <table class="table striped">
      <thead>
        <th>Order ID</th>
        <th>Order Items</th>
        <th>Table No.</th>
        <th>Waiter</th>
        <th>Order Total</th>
        <th>Payment</th>
        <td>Status</td>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.order_id %></td>
            <td>
              <div class="tooltip">
                <button class="btn white" onclick="order_items(<%= order.order_id %>)">View Order Items(<%= order.order_items.count %>)</button>
                <span class="tooltiptext">Click</span>
              </div>
              <div id="order_items<%= order.order_id %>" style="display: none">
                <% order.order_items.each do |item| %>
                <li><%= item.menu.item_name %>   <span style="float: right"><%= number_to_currency(item.menu.item_cost, unit: "KES ") %></span> </li>
                <% end %>
                <button class="x" onclick="xorder(<%= order.order_id %>)">X</button>
              </div>
            </td>
            <td><%= order.table_no %></td>
            <td><%= ["John", "Ali"].sample %></td>
            <td><%= number_to_currency(order.order_cost, unit: "KES ") %></td>
            <td>
              <div class="tooltip">
                <button class="btn white" onclick="payments(<%= order.order_id %>)" name="button">(<%= order.transactions.count %>) view payments</button>
                <span class="tooltiptext">Click</span>
              </div>
              <div id="payments<%= order.order_id %>" style="display: none">
                <% order.transactions.each do |transaction| %>
                  <li><%= transaction.transaction_id %> MP3S4R3F <span style="float: right"><%= number_to_currency(transaction.transaction_amount, unit: "KES ") %></span> </li>
                <% end %>
                <button class="x" onclick="xtransaction(<%= order.order_id %>)">X</button>
              </div>
            </td>
            <% if order.order_cost == order.transactions.sum(:transaction_amount) %>
              <td> <p>Paid</p> </td>
            <% else %>
              <td> <p><%= number_to_currency((order.order_cost - order.transactions.sum(:transaction_amount)), unit: "KES ") %></p> </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @orders %>

  <!-- else %> -->
    <d<!-- iv class="warning">
      <p>Contact admin to gain access</p>
    </ -->div>
   <!-- end %> -->

app/views/dashboard/transactions.html.erb
<h1>History</h1>
 <!-- if account_signed_in? || cashier_signed_in? %> -->
<h5>Filter Data</h5>
<div class="filter-form">
  <form class="" action="index.html" method="post">
    <div class="row">
      <div class="col s5">
        <input type="text" name="" value="start date">
      </div>
      <div class="col s5">
        <input type="text" name="" value="end date">
      </div>
      <div class="col s2">
        <button class="btn white" type="button" name="button">search</button>
      </div>
    </div>

  </form>
</div>
<div class="search">
  <div class="row">
    <div class="col 11">
      <input type="text" name="" placeholder="Enter Transaction Ref/ Order Ref or Phone No.">
    </div>
    <div class="col 1">
      <a href="#"><i class="material-icons">search</i></a>
    </div>
  </div>
</div>
  <h1>Orders</h1>
  <table class="table striped">
    <thead>
      <th>Order ID</th>
      <th>Order Items</th>
      <th>Table No.</th>
      <th>Waiter</th>
      <th>Order Total</th>
      <th>Payment</th>
      <td>Status</td>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.order_id %></td>
          <td>
            <div class="tooltip">
              <button class="btn white" onclick="order_items(<%= order.order_id %>)">View Order Items(<%= order.order_items.count %>)</button>
              <span class="tooltiptext">Click</span>
            </div>
            <div id="order_items<%= order.order_id %>" style="display: none">
              <% order.order_items.each do |item| %>
              <li><%= item.menu.item_name %>   <span style="float: right"><%= number_to_currency(item.menu.item_cost, unit: "KES ") %></span> </li>
              <% end %>
              <button onclick="xorder(<%= order.order_id %>)">X</button>
            </div>
          </td>
          <td><%= order.table_no %></td>
          <td><%= ["John", "Ali"].sample %></td>
          <td><%= number_to_currency(order.order_cost, unit: "KES ") %></td>
          <td>
            <div class="tooltip">
              <button class="btn white" onclick="payments(<%= order.order_id %>)" name="button">(<%= order.transactions.count %>) view payments</button>
              <span class="tooltiptext">Click</span>
            </div>
            <div id="payments<%= order.order_id %>" style="display: none">
              <% order.transactions.each do |transaction| %>
                <li><%= transaction.transaction_id %> MP3S4R3F <span style="float: right"><%= number_to_currency(transaction.transaction_amount, unit: "KES ") %></span> </li>
              <% end %>
              <button onclick="xtransaction(<%= order.order_id %>)">X</button>
            </div>
          </td>
          <% if order.order_cost == order.transactions.sum(:transaction_amount) %>
            <td> <p>Paid</p> </td>
          <% else %>
            <td> <p><%= number_to_currency((order.order_cost - order.transactions.sum(:transaction_amount)), unit: "KES ") %></p> </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @orders %>

<!--  else %>
  <div class="warning">
    <p>Contact admin to gain access</p>
  </div>
 end %>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlYusra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="side-nav">
      <div class="logo">
        <a href="/"><%= image_tag 'logo' %></a>
          <div class="accounts">
            <p>Transactions Portal</p>
            <% if account_signed_in? %>
            Welcome <%= current_account.email %>
            <!-- <%= link_to "Log Out", destroy_account_session_path, method: 'DELETE'%> -->
            <% end %>
            <% if cashier_signed_in? %>
            Welcome <%= current_cashier.email %>
            <!-- <%= link_to "Log Out", destroy_cashier_session_path, method: 'DELETE'%> -->
            <% end %>
          </div>
      </div>
      <div class="side-menu">
        <li><%= link_to "Transactions", history_path %></li>
        <% if account_signed_in? %>
          <li><%= link_to "Log Out", destroy_account_session_path, method: 'DELETE'%></li>
        <% end %>
        <% if cashier_signed_in? %>
          <li><%= link_to "Log Out", destroy_cashier_session_path, method: 'DELETE'%></li>
        <% end %>
      </div>
    </div>
    <div class="main">
        <%= yield %>
        <footer>
          <h4>Daily Trends</h4>
          <div class="row">
            <div class="col s4">
              <h6>Top Selling Waiters</h6>
              <ol>
                <li>Ali - <%= rand(40..50) %> Orders - Total: <%= number_to_currency(rand(10000..40000), unit: "KES ") %></li>
                <li>John - <%= rand(30..40) %> Orders - Total: <%= number_to_currency(rand(10000..40000), unit: "KES ") %></li>
                <li>Moses - <%= rand(20..30) %> Orders - Total: <%= number_to_currency(rand(10000..40000), unit: "KES ") %></li>
              </ol>
            </div>
            <div class="col s4">
              <h6>Top Selling Foods</h6>
              <ol>
                <% @topfoods = OrderItem.order("order_id DESC").offset(3).limit(3) %>
                <% @topfoods.each do |food| %>
                  <li><%= food.menu.item_name %> - <%= OrderItem.where(menu_id: food.menu_id).count %> - <%= number_to_currency(OrderItem.where(menu_id: food.menu_id).count * Menu.find(food.menu_id).item_cost, unit: 'KES ') %></li>
                <% end %>
              </ol>
            </div>
            <div class="col s4">
              <h6>Top Favourite Tables</h6>
              <ol>
                <li>table 10 - KES 76,000</li>
                <li>table 03 - KES 45,500</li>
                <li>table 15 - KES 42,000</li>
              </ol>
            </div>
          </div>
        </footer>
    </div>
  </body>
</html>